var express = require("express");
var router = express.Router();
var Makhdoumin = require("./../models/makhdoumin");
var servants = require("./../models/servants");
/* GET users listing. */
router.get("/", function (req, res, next) {
  res.send("respond with a resource");
});

router.post("/addUser", function (req, res, next) {
  Makhdoumin.create(req.body, function (err, post) {
    if (err) return next(err);
    res.json(post);
  });
});
router.post("/addServants", function (req, res, next) {

  servants.create(req.body, function (err, post) {
    if (err) return next(err);
    res.json(post);
  });
});
router.post("/addDummy", function (req, res, next) {
  var AllMakhdouminData = [{
      "counter": "1",
      "class": "ثانية",
      "zone": "A",
      "name": "يـوسف مدحـت فــــرج ",
      "buildingNumber": "5",
      "streetName": "شارع الجد",
      "floorNumber": "2",
      "flatNumber": "10",
      "MobilePhone": "1203702999",
      "HomePhone": "27879256",
      "birthDate": "11-03-00",
      "fatherOfConfession": "ابونا يوسف",
      "servantFollowing": "أ. بيشوى",
      "chomosya": "ابصالتس",
      "school": "القديس ميخائيل",
      "facebook": "youssef Medhat ",
      "email": "",
      "fatherPhone": "1229361392",
      "motherPhone": "1207250271",
      "notes": "",
      "lastupdate": "",
      "remarks": "test"
    },
    {
      "counter": "2",
      "class": "ثانية",
      "zone": "A",
      "name": "رؤوف عزيز كمــال",
      "buildingNumber": "32",
      "streetName": "شارع الجد",
      "floorNumber": "4",
      "flatNumber": "-",
      "MobilePhone": "1210770402",
      "HomePhone": "25887998",
      "birthDate": "11-03-01",
      "fatherOfConfession": "ابونا برسوم",
      "servantFollowing": "أ. بيشوى",
      "chomosya": "ابصالتس",
      "school": "القديس ميخائيل",
      "facebook": "Raouf Aziz ",
      "email": "raoufaziz88@gmail.com",
      "fatherPhone": "1222225417",
      "motherPhone": "1202225127",
      "notes": "",
      "lastupdate": "",
      "remarks": ""
    },
    {
      "counter": "3",
      "class": "ثانية",
      "zone": "A",
      "name": "رويس رضـا انـدراوس",
      "buildingNumber": "21",
      "streetName": "شارع يوسف وهبي",
      "floorNumber": "9",
      "flatNumber": "40",
      "MobilePhone": "1284668695",
      "HomePhone": "27864564",
      "birthDate": "01-15-00",
      "fatherOfConfession": "ابونا انجيلوس",
      "servantFollowing": "أ. مينا نادى",
      "chomosya": "ابصالتس",
      "school": "البطريركية",
      "facebook": "Rowace R. Andraws",
      "email": "rowacereda@hotmail.com",
      "fatherPhone": "",
      "motherPhone": "1205993995",
      "notes": "",
      "lastupdate": "",
      "remarks": ""
    },
    {
      "counter": "4",
      "class": "ثانية",
      "zone": "A",
      "name": "كيرلس نشــات حنا",
      "buildingNumber": "25",
      "streetName": "شارع الجميل",
      "floorNumber": "1",
      "flatNumber": "1 ى ",
      "MobilePhone": "1023211556",
      "HomePhone": "25886615",
      "birthDate": "10-10-00",
      "fatherOfConfession": "ابونا تادرس",
      "servantFollowing": "أ. بيشوى",
      "chomosya": "ابصالتس",
      "school": "صحارة للغات",
      "facebook": "Kirolous Nashaat ",
      "email": "kirolouss@gmail.com",
      "fatherPhone": "1227003932",
      "motherPhone": "",
      "notes": "",
      "lastupdate": "",
      "remarks": ""
    },
    {
      "counter": "5",
      "class": "ثانية",
      "zone": "A",
      "name": "جـــورج منـير عــريان",
      "buildingNumber": "4",
      "streetName": "شارع ابن بركة",
      "floorNumber": "4",
      "flatNumber": "18",
      "MobilePhone": "1281810903",
      "HomePhone": "25884710",
      "birthDate": "03-09-01",
      "fatherOfConfession": "ابونا انجيلوس",
      "servantFollowing": "أ. بيتر ",
      "chomosya": "ابصالتس",
      "school": "صحارة للغات",
      "facebook": "George Mounir ",
      "email": "george_2222@hotmail.com",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "",
      "lastupdate": "",
      "remarks": ""
    },
    {
      "counter": "6",
      "class": "ثانية",
      "zone": "A",
      "name": "مايكل جرجس أنيــس",
      "buildingNumber": "4",
      "streetName": "سكة الجميل",
      "floorNumber": "5",
      "flatNumber": "18",
      "MobilePhone": "1200943892",
      "HomePhone": "2786879",
      "birthDate": "04-06-01",
      "fatherOfConfession": "ابونا انجيلوس",
      "servantFollowing": "أ. بيشوى",
      "chomosya": "ابصالتس",
      "school": "القديس ميخائيل",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "",
      "lastupdate": "",
      "remarks": ""
    },
    {
      "counter": "7",
      "class": "ثانية",
      "zone": "A",
      "name": "جورج ميشيل ميخائيل",
      "buildingNumber": "23",
      "streetName": "شارع غالي",
      "floorNumber": "6",
      "flatNumber": "17ش",
      "MobilePhone": "1200556783",
      "HomePhone": "لا يوجد",
      "birthDate": "22/10/2000",
      "fatherOfConfession": "ابونا انجيلوس",
      "servantFollowing": "أ. إبراهيم",
      "chomosya": "ابصالتس",
      "school": "عاطف صدقى التجريبية مصر الجديدة",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "",
      "lastupdate": "",
      "remarks": ""
    },
    {
      "counter": "8",
      "class": "ثانية",
      "zone": "A",
      "name": "جـورج اسحـاق دميــان",
      "buildingNumber": "15",
      "streetName": "شارع غالي",
      "floorNumber": "3",
      "flatNumber": "10",
      "MobilePhone": "1226695635",
      "HomePhone": "25890893",
      "birthDate": "10-06-01",
      "fatherOfConfession": "ابونا يوسف",
      "servantFollowing": "أ. إبراهيم",
      "chomosya": "ابصالتس",
      "school": "الراعى الصالح",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "",
      "lastupdate": "",
      "remarks": ""
    },
    {
      "counter": "9",
      "class": "ثانية",
      "zone": "A",
      "name": "باسم اشرف ( أيمن يوسف )",
      "buildingNumber": "7",
      "streetName": "شارع غالي",
      "floorNumber": "ارضي",
      "flatNumber": "",
      "MobilePhone": "1279714297",
      "HomePhone": "25904997",
      "birthDate": "02-07-00",
      "fatherOfConfession": "ابونا برسوم",
      "servantFollowing": "أ. مينا نادى",
      "chomosya": "غير مرشوم ",
      "school": "النظام",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "الملجأ",
      "lastupdate": "30-Oct-2016",
      "remarks": ""
    },
    {
      "counter": "10",
      "class": "ثانية",
      "zone": "A",
      "name": "مــارك ايهــاب شكــرى",
      "buildingNumber": "17",
      "streetName": "شارع يوسف سليمان",
      "floorNumber": "1",
      "flatNumber": "3",
      "MobilePhone": "1203921024",
      "HomePhone": "25916841",
      "birthDate": "12-13-00",
      "fatherOfConfession": "ابونا برسوم",
      "servantFollowing": "أ. بيتر ",
      "chomosya": "ابصالتس",
      "school": "صحارة للغات",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "",
      "lastupdate": "2-Nov-2014",
      "remarks": ""
    },
    {
      "counter": "11",
      "class": "ثانية",
      "zone": "A",
      "name": "ابانوب كامل",
      "buildingNumber": "",
      "streetName": "عمارة كيرومينا",
      "floorNumber": "الأرضى",
      "flatNumber": "-",
      "MobilePhone": "1225455232",
      "HomePhone": "",
      "birthDate": "",
      "fatherOfConfession": "ابونا انجيلوس",
      "servantFollowing": "أ. مينا نادى",
      "chomosya": "",
      "school": "",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "",
      "lastupdate": "",
      "remarks": ""
    },
    {
      "counter": "12",
      "class": "ثانية",
      "zone": "B",
      "name": "يوســف مكـــرم نصــر",
      "buildingNumber": "8",
      "streetName": "حارة ابا الحارث",
      "floorNumber": "4",
      "flatNumber": "ي",
      "MobilePhone": "1201863730",
      "HomePhone": "27877844",
      "birthDate": "10-30-00",
      "fatherOfConfession": "ابونا يوسف",
      "servantFollowing": "أ. مينا نادى",
      "chomosya": "غير مرشوم ",
      "school": "الفاروق عمر",
      "facebook": "Youssef Joo",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "1224797554",
      "notes": "الاب متوفى - حالة خاصة",
      "lastupdate": "",
      "remarks": ""
    },
    {
      "counter": "13",
      "class": "ثانية",
      "zone": "B",
      "name": "باســم شكــرى يــوسف",
      "buildingNumber": "19",
      "streetName": "حارة نسب",
      "floorNumber": "10",
      "flatNumber": "24",
      "MobilePhone": "1279620449",
      "HomePhone": "25920602",
      "birthDate": "07-04-01",
      "fatherOfConfession": "ابونا يوسف",
      "servantFollowing": "أ. إبراهيم",
      "chomosya": "ابصالتس",
      "school": "القديس ميخائيل",
      "facebook": "Beso Shokry ",
      "email": "shokry.youssef@yahoo.com",
      "fatherPhone": "1223627810",
      "motherPhone": "",
      "notes": "",
      "lastupdate": "",
      "remarks": ""
    },
    {
      "counter": "14",
      "class": "ثانية",
      "zone": "B",
      "name": "جــورج بــاســم كـامـل",
      "buildingNumber": "13",
      "streetName": "يوسف سليمان",
      "floorNumber": "3",
      "flatNumber": "10",
      "MobilePhone": "1159477925",
      "HomePhone": "",
      "birthDate": "20/10/2001",
      "fatherOfConfession": "ابونا انجيلوس",
      "servantFollowing": "أ. إبراهيم",
      "chomosya": "ابصالتس",
      "school": "مصر 2000 التجمع الخامس",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "",
      "lastupdate": "2-Nov-2014",
      "remarks": ""
    },
    {
      "counter": "15",
      "class": "ثانية",
      "zone": "B",
      "name": "مكسيموس مدحت مفـــيد",
      "buildingNumber": "4",
      "streetName": "ببطرس غالى ",
      "floorNumber": "3",
      "flatNumber": "5",
      "MobilePhone": "1279457242",
      "HomePhone": "25931195",
      "birthDate": "05-29-01",
      "fatherOfConfession": "ابونا موسى",
      "servantFollowing": "أ. بيتر ",
      "chomosya": "ابصالتس",
      "school": "صحارة للغات",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "",
      "lastupdate": "2-Nov-2014",
      "remarks": ""
    },
    {
      "counter": "16",
      "class": "ثانية",
      "zone": "B",
      "name": "صموئيل نصحي حبيب",
      "buildingNumber": "16",
      "streetName": "شارع بركة الرطل",
      "floorNumber": "6",
      "flatNumber": "22ش",
      "MobilePhone": "1226715009",
      "HomePhone": "25909056",
      "birthDate": "09-07-01",
      "fatherOfConfession": "ابونا انجيلوس",
      "servantFollowing": "أ. مينا نادى",
      "chomosya": "ابصالتس",
      "school": "التوفيق",
      "facebook": "Samuel Noshy ",
      "email": "samuel88@yahoo.com",
      "fatherPhone": "1223340604",
      "motherPhone": "1220670690",
      "notes": "",
      "lastupdate": "2-Nov-2014"
    },
    {
      "counter": "17",
      "class": "ثانية",
      "zone": "B",
      "name": "ابـانوب اسـامة سمير",
      "buildingNumber": "10",
      "streetName": "حارة بستان التاج",
      "floorNumber": "1",
      "flatNumber": "2",
      "MobilePhone": "1202675985",
      "HomePhone": "25889046",
      "birthDate": "05-19-01",
      "fatherOfConfession": "ابونا برسوم",
      "servantFollowing": "أ. بيتر ",
      "chomosya": "ابصالتس",
      "school": "القديس ميخائيل",
      "facebook": "Bibo.Abanob osama ",
      "email": "",
      "fatherPhone": "1227555042",
      "motherPhone": "",
      "notes": "",
      "lastupdate": "2-Nov-2014"
    },
    {
      "counter": "18",
      "class": "ثانية",
      "zone": "B",
      "name": "فيلوبتير مخلص يونان",
      "buildingNumber": "3",
      "streetName": "سكة البشنيني",
      "floorNumber": "8",
      "flatNumber": "16",
      "MobilePhone": "1226444896",
      "HomePhone": "25913916",
      "birthDate": "11-08-00",
      "fatherOfConfession": "ابونا انجيلوس",
      "servantFollowing": "أ. بيشوى",
      "chomosya": "ابصالتس",
      "school": "نيو رمسيس ",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "",
      "lastupdate": "30-Oct-2016"
    },
    {
      "counter": "19",
      "class": "ثانية",
      "zone": "B",
      "name": "يوسف سعد لطفى",
      "buildingNumber": "3",
      "streetName": "بستان التاج",
      "floorNumber": "2",
      "flatNumber": "6",
      "MobilePhone": "1279122664",
      "HomePhone": "",
      "birthDate": "08-03-00",
      "fatherOfConfession": "ابونا انجيلوس",
      "servantFollowing": "أ. إبراهيم",
      "chomosya": "ابصالتس",
      "school": "بطريركية",
      "facebook": "youssef saad ",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "تأخر دراسى",
      "lastupdate": "11-Jan-2015"
    },
    {
      "counter": "20",
      "class": "ثانية",
      "zone": "B",
      "name": "كيرلس روماني سليمان",
      "buildingNumber": "5",
      "streetName": "ميدان بركة الرطل",
      "floorNumber": "2",
      "flatNumber": "7ش",
      "MobilePhone": "1280926434",
      "HomePhone": "25880822",
      "birthDate": "01-06-00",
      "fatherOfConfession": "ابونا انجيلوس",
      "servantFollowing": "أ. بيشوى",
      "chomosya": "ابصالتس",
      "school": "النصر التجريبية ميدان الجيش",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "",
      "lastupdate": ""
    },
    {
      "counter": "21",
      "class": "ثانية",
      "zone": "B",
      "name": "ايـلي جــورج ناصـوح",
      "buildingNumber": "2",
      "streetName": "ميدان بركة الرطل",
      "floorNumber": "9",
      "flatNumber": "26",
      "MobilePhone": "1061811042",
      "HomePhone": "27872290",
      "birthDate": "06-25-00",
      "fatherOfConfession": "ابونا موسي نيروز",
      "servantFollowing": "أ. إبراهيم",
      "chomosya": "ابصالتس",
      "school": "الدى لاسال",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "",
      "lastupdate": ""
    },
    {
      "counter": "22",
      "class": "ثانية",
      "zone": "B",
      "name": "مايكـل عصـام عـريــان",
      "buildingNumber": "25",
      "streetName": "شارع حبيب شلبي",
      "floorNumber": "6",
      "flatNumber": "2",
      "MobilePhone": "1286044794",
      "HomePhone": "25922593",
      "birthDate": "08-24-00",
      "fatherOfConfession": "ابونا انجيلوس",
      "servantFollowing": "أ. إبراهيم",
      "chomosya": "ابصالتس",
      "school": "البطريركية",
      "facebook": "",
      "email": "",
      "fatherPhone": "1226483303",
      "motherPhone": "1227867656",
      "notes": "",
      "lastupdate": ""
    },
    {
      "counter": "23",
      "class": "ثانية",
      "zone": "C",
      "name": "ابانوب ميخائيل",
      "buildingNumber": "75",
      "streetName": "القبيسي",
      "floorNumber": "4",
      "flatNumber": "21",
      "MobilePhone": "1204314087",
      "HomePhone": "25894753",
      "birthDate": "12-03-00",
      "fatherOfConfession": "ابونا يوسف",
      "servantFollowing": "أ. بيتر ",
      "chomosya": "",
      "school": "اسماعيل القبانى",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "12206600269",
      "notes": "عنده كشافة فى ميعاد الخدمة - السريان ",
      "lastupdate": "15-11-2016"
    },
    {
      "counter": "24",
      "class": "ثانية",
      "zone": "C",
      "name": "جيوفاني انطون بشرى",
      "buildingNumber": "22ب",
      "streetName": "شارع صبري",
      "floorNumber": "4",
      "flatNumber": "13",
      "MobilePhone": "1202090683",
      "HomePhone": "25901960",
      "birthDate": "03-24-01",
      "fatherOfConfession": "ابونا انجيلوس",
      "servantFollowing": "أ. بيتر ",
      "chomosya": "ابصالتس",
      "school": "القديس ميخائيل",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "عنده درس الساعة 6:30",
      "lastupdate": "24-Oct-2015"
    },
    {
      "counter": "25",
      "class": "ثانية",
      "zone": "C",
      "name": "يوسف مجدى موريس ",
      "buildingNumber": "15",
      "streetName": "شارع ذهنى",
      "floorNumber": "2",
      "flatNumber": "4",
      "MobilePhone": "1006456732",
      "HomePhone": "27873613",
      "birthDate": "",
      "fatherOfConfession": "ابونا انجيلوس",
      "servantFollowing": "أ. بيشوى",
      "chomosya": "",
      "school": "القديس ميخائيل",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "",
      "lastupdate": "2-Nov-2014"
    },
    {
      "counter": "26",
      "class": "ثانية",
      "zone": "C",
      "name": "بيتــر اشــرف صـــليب",
      "buildingNumber": "4",
      "streetName": "حارة العرقبجى بجوار تبارك",
      "floorNumber": "5",
      "flatNumber": "9",
      "MobilePhone": "1123051651",
      "HomePhone": "",
      "birthDate": "",
      "fatherOfConfession": "",
      "servantFollowing": "أ. بيتر ",
      "chomosya": "",
      "school": "القديس ميخائيل",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "بيروح كشافة السريان",
      "lastupdate": "30-Oct-2016"
    },
    {
      "counter": "27",
      "class": "ثانية",
      "zone": "C",
      "name": "شــادي ايهـــاب زكـريا",
      "buildingNumber": "13أ",
      "streetName": "شارع مراد",
      "floorNumber": "1",
      "flatNumber": "وش",
      "MobilePhone": "101384996",
      "HomePhone": "27878879",
      "birthDate": "06-28-01",
      "fatherOfConfession": "ابونا انجيلوس",
      "servantFollowing": "أ. بيشوى",
      "chomosya": "",
      "school": "المبتديان",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "السريان ",
      "lastupdate": "30-Oct-2016"
    },
    {
      "counter": "28",
      "class": "ثانية",
      "zone": "C",
      "name": "رضا ملاك",
      "buildingNumber": "4",
      "streetName": "شارع حمدي",
      "floorNumber": "ارضي",
      "flatNumber": "-",
      "MobilePhone": "1124513257",
      "HomePhone": "",
      "birthDate": "04-07-01",
      "fatherOfConfession": "ابونا انجيلوس",
      "servantFollowing": "أ. مينا نادى",
      "chomosya": "لا",
      "school": "السيدة - السلام",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "",
      "lastupdate": ""
    },
    {
      "counter": "29",
      "class": "ثانية",
      "zone": "C",
      "name": "جورج عادل جورج",
      "buildingNumber": "18",
      "streetName": "شارع ارض الامامين",
      "floorNumber": "2",
      "flatNumber": "2",
      "MobilePhone": "1283367491",
      "HomePhone": "",
      "birthDate": "05-20-01",
      "fatherOfConfession": "ابونا يوسف",
      "servantFollowing": "أ. بيشوى",
      "chomosya": "ابصالتس",
      "school": "اسماعيل القبانى",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "1227242786",
      "notes": "قاعد معظم الوقت فى عمارة الجمعية الدور الأخير. (جدته)",
      "lastupdate": "30-Oct-2016"
    },
    {
      "counter": "30",
      "class": "ثانية",
      "zone": "C",
      "name": "ميلاد استمالك",
      "buildingNumber": "23",
      "streetName": "شارع الظاهر",
      "floorNumber": "ارضي",
      "flatNumber": "",
      "MobilePhone": "1205323157",
      "HomePhone": "",
      "birthDate": "01-02-00",
      "fatherOfConfession": "ابونا يوسف",
      "servantFollowing": "أ. مينا نادى",
      "chomosya": "ابصالتس",
      "school": "الراعى الصالح",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "والده متوفى - سجائر - عاملين - تأخر دراسى",
      "lastupdate": "30-Oct-2016"
    },
    {
      "counter": "31",
      "class": "ثانية",
      "zone": "C",
      "name": "انتوني جرجس منقاريوس",
      "buildingNumber": "49",
      "streetName": "القبيسي",
      "floorNumber": "7",
      "flatNumber": "7",
      "MobilePhone": "1272634063",
      "HomePhone": "25883224",
      "birthDate": "03-17-02",
      "fatherOfConfession": "ابونا انجيلوس",
      "servantFollowing": "أ. بيتر ",
      "chomosya": "ابصالتس",
      "school": "المارونية",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "",
      "lastupdate": ""
    },
    {
      "counter": "32",
      "class": "ثانية",
      "zone": "C",
      "name": "اندرو ادورد",
      "buildingNumber": "15",
      "streetName": "ذهني",
      "floorNumber": "3",
      "flatNumber": "5",
      "MobilePhone": "1287261046",
      "HomePhone": "",
      "birthDate": "",
      "fatherOfConfession": "ابونا يوسف",
      "servantFollowing": "أ. بيشوى",
      "chomosya": "ابصالتس",
      "school": "غمرة ثانوية بنين",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "1201039747",
      "notes": "",
      "lastupdate": "30-Oct-2016"
    },
    {
      "counter": "33",
      "class": "ثانية",
      "zone": "C",
      "name": "فــادي جمـيل سعــد",
      "buildingNumber": "24",
      "streetName": "شارع القبيسي",
      "floorNumber": "5",
      "flatNumber": "5",
      "MobilePhone": "0122637641رقم أخوه",
      "HomePhone": "25924330",
      "birthDate": "05-22-00",
      "fatherOfConfession": "",
      "servantFollowing": "أ. مينا نادى",
      "chomosya": "",
      "school": "الجلاء التجريبية",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "محتاج يكون ليه أصحاب",
      "lastupdate": "30-Oct-2016"
    },
    {
      "counter": "34",
      "class": "ثانية",
      "zone": "C",
      "name": "مارتن امير ",
      "buildingNumber": "4",
      "streetName": "شارع زغلول",
      "floorNumber": "1",
      "flatNumber": "1",
      "MobilePhone": "",
      "HomePhone": "25886882",
      "birthDate": "10-19-00",
      "fatherOfConfession": "",
      "servantFollowing": "أ. بيشوى",
      "chomosya": "",
      "school": "صحارة للغات",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "بيحضر فى معهد الدراسات فى الشرابية فى ميعاد الخدمة",
      "lastupdate": ""
    },
    {
      "counter": "35",
      "class": "ثانية",
      "zone": "C",
      "name": "يوسف سامح",
      "buildingNumber": "13",
      "streetName": "صبرى ",
      "floorNumber": "8",
      "flatNumber": "81",
      "MobilePhone": "",
      "HomePhone": "27863747",
      "birthDate": "",
      "fatherOfConfession": "ابونا اسطفانوس (المنسى )",
      "servantFollowing": "أ. بيتر ",
      "chomosya": "غير مرشوم ",
      "school": "المارونية",
      "facebook": "youssef farouk ",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "1094829904",
      "notes": "باباه شغال بره - بيروح كنيسة فى باب الشعرية",
      "lastupdate": "30-Oct-2016"
    },
    {
      "counter": "36",
      "class": "ثانية",
      "zone": "C",
      "name": "مينــا صفـوت ثـابت",
      "buildingNumber": "22",
      "streetName": "حمدي",
      "floorNumber": "5",
      "flatNumber": "ش",
      "MobilePhone": "1550619262",
      "HomePhone": "",
      "birthDate": "02-03-02",
      "fatherOfConfession": "ابونا انجيلوس",
      "servantFollowing": "أ. بيشوى",
      "chomosya": "ابصالتس",
      "school": "",
      "facebook": "",
      "email": "",
      "fatherPhone": "1225601263",
      "motherPhone": "",
      "notes": "",
      "lastupdate": ""
    },
    {
      "counter": "37",
      "class": "ثانية",
      "zone": "D",
      "name": "امجد منصور",
      "buildingNumber": "3",
      "streetName": "عطفية بكر القذاذ- الجيش",
      "floorNumber": "الاخير",
      "flatNumber": "ش",
      "MobilePhone": "1275233037",
      "HomePhone": "",
      "birthDate": "",
      "fatherOfConfession": "",
      "servantFollowing": "أ. مينا نادى",
      "chomosya": "ابصالتس",
      "school": "عمر بن العاص",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "مشاكل فى البيت",
      "lastupdate": "30-Oct-2016"
    },
    {
      "counter": "38",
      "class": "ثانية",
      "zone": "D",
      "name": "مارك ميلاد",
      "buildingNumber": "58",
      "streetName": "بورسعيد ( برج المنير ) ",
      "floorNumber": "7",
      "flatNumber": "",
      "MobilePhone": "1069527849",
      "HomePhone": "24237623",
      "birthDate": "04-02-01",
      "fatherOfConfession": "ابونا انجيلوس",
      "servantFollowing": "أ. إبراهيم",
      "chomosya": "غير مرشوم ",
      "school": "",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "",
      "lastupdate": ""
    },
    {
      "counter": "39",
      "class": "ثانية",
      "zone": "D",
      "name": "مارك عماد",
      "buildingNumber": "21",
      "streetName": "ابن الرشيد - جزيرة بدران - شبرا",
      "floorNumber": "4",
      "flatNumber": "19",
      "MobilePhone": "1005664024",
      "HomePhone": "",
      "birthDate": "June 7",
      "fatherOfConfession": " 2000",
      "servantFollowing": "ابونا انجيلوس",
      "chomosya": "أ. بيتر ",
      "school": "ابصالتس",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "",
      "lastupdate": "والده توفى فى حادثة - قريب ستيفن",
      "remarks": "30-Oct-2016"
    },
    {
      "counter": "40",
      "class": "ثانية",
      "zone": "D",
      "name": "صموئيل عيد",
      "buildingNumber": "4",
      "streetName": "شارع جعفر ",
      "floorNumber": "الارضى ",
      "flatNumber": "",
      "MobilePhone": "1207536972",
      "HomePhone": "",
      "birthDate": "17/9/2001",
      "fatherOfConfession": "لا يوجد",
      "servantFollowing": "أ. إبراهيم",
      "chomosya": "غير مرشوم ",
      "school": "غمرة ثانوية بنين",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "عنده مشكلة كبيرة و محتاجين نحط اسمه على المذبح",
      "lastupdate": "24/10/2015"
    },
    {
      "counter": "41",
      "class": "ثانية",
      "zone": "D",
      "name": "ميخائيل عادل",
      "buildingNumber": "13",
      "streetName": "شارع صافى الدين المهرانى - بستان المهاميز",
      "floorNumber": "3",
      "flatNumber": "6",
      "MobilePhone": "1149967188",
      "HomePhone": "",
      "birthDate": "",
      "fatherOfConfession": "أبونا مسى - الفجالة",
      "servantFollowing": "أ. بيتر ",
      "chomosya": "شماس",
      "school": "صحارا",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "بيروح الفجالة أكتر فى الشتاء و بيجيلنا قليل",
      "lastupdate": "15-11-2016"
    },
    {
      "counter": "42",
      "class": "ثانية",
      "zone": "D",
      "name": "جرجس صبحي",
      "buildingNumber": "6",
      "streetName": "عطفة الخربوطلي - الظاهر",
      "floorNumber": "",
      "flatNumber": "",
      "MobilePhone": "1283631901",
      "HomePhone": "",
      "birthDate": "18/11/2001",
      "fatherOfConfession": "ابونا انجيلوس",
      "servantFollowing": "",
      "chomosya": "غير مرشوم ",
      "school": "",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "",
      "lastupdate": ""
    },
    {
      "counter": "43",
      "class": "ثانية",
      "zone": "D",
      "name": "وليد مجدي (وليد عياد)",
      "buildingNumber": "",
      "streetName": "",
      "floorNumber": "",
      "flatNumber": "",
      "MobilePhone": "",
      "HomePhone": "",
      "birthDate": "",
      "fatherOfConfession": "",
      "servantFollowing": "",
      "chomosya": "",
      "school": "",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "",
      "lastupdate": ""
    },
    {
      "counter": "44",
      "class": "ثانية",
      "zone": "D",
      "name": "ابانوب عيسى",
      "buildingNumber": "",
      "streetName": "",
      "floorNumber": "",
      "flatNumber": "",
      "MobilePhone": "",
      "HomePhone": "",
      "birthDate": "",
      "fatherOfConfession": "",
      "servantFollowing": "",
      "chomosya": "",
      "school": "",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "",
      "lastupdate": ""
    },
    {
      "counter": "45",
      "class": "ثانية",
      "zone": "D",
      "name": "كيرلس جورج",
      "buildingNumber": "",
      "streetName": "",
      "floorNumber": "",
      "flatNumber": "",
      "MobilePhone": "",
      "HomePhone": "",
      "birthDate": "",
      "fatherOfConfession": "",
      "servantFollowing": "",
      "chomosya": "",
      "school": "",
      "facebook": "",
      "email": "",
      "fatherPhone": "",
      "motherPhone": "",
      "notes": "",
      "lastupdate": ""
    },
    {
      "counter": ""
    }
  ]
  async function runAsync(testowow) {
   

    await Makhdoumin.create(testowow);
  }
  AllMakhdouminData.forEach(function (eachMakhdoum) {

    let makhdouminWillBeReshaped = {
      "personalInfo": {
        "name": eachMakhdoum.name,
        "address": {
          "buildingNumber": eachMakhdoum.buildingNumber,
          "streetName": eachMakhdoum.streetName,
          "floorNumber": eachMakhdoum.floorNumber,
          "flatNumber": eachMakhdoum.flatNumber,
          "zone": eachMakhdoum.zone,
          "remarks": eachMakhdoum.remarks
        },
        "Mobiles": {
          "MobilePhone": eachMakhdoum.MobilePhone,
          "HomePhone": eachMakhdoum.HomePhone,
          "fatherPhone": eachMakhdoum.fatherPhone,
          "motherPhone": eachMakhdoum.motherPhone
        },
        "school": eachMakhdoum.school,
        "birthDate": "2000-08-24T00:00:00.000Z",
        "onlineInfo": {
          "facebook": eachMakhdoum.facebook,
          "email": eachMakhdoum.email
        }
      },
      "churchAndSpiritualInfo": {
        "class": eachMakhdoum.class,
        "fatherOfConfession": eachMakhdoum.fatherOfConfession,
        "servantFollowing": eachMakhdoum.servantFollowing,
        "chomosya": eachMakhdoum.chomosya,
        "Notes": eachMakhdoum.Notes
      }

    }
    runAsync(makhdouminWillBeReshaped)



  })

});
module.exports = router;